export const AUTH_REQ = "AUTH_REQ";
export const AUTH_REQ_SUCCESS = "AUTH_REQ_SUCCESS";
export const AUTH_REQ_FAILURE = "AUTH_REQ_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNOUT = "SIGNOUT";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

// POST
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS";

// GET
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";

// PATCH
export const PRODUCT_PATCH_SUCCESS = "PRODUCT_PATCH_SUCCESS";

// DELETE
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
