export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

// POST
export const PRODUCT_POST_SUCCESS = "PRODUCT_POST_SUCCESS";

// GET
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";

// PATCH
export const PRODUCT_PATCH_SUCCESS = "PRODUCT_PATCH_SUCCESS";

// DELETE
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
